#!/bin/bash
set -x

###install essential packages

install_essential(){

sudo apt-get update
sudo apt-get install git software-properties-common build-essential apt-transport-https \
wget curl zip unzip bzip2 rar unrar openssh-client \
htop facter ohai net-tools lsof htop tcpdump screen \
nmap wireshark nemesis nessus \
automake autoconf maven gradle ant -y

}

###install python and pip

install_python_pip() {

sudo apt-get install python-dev python-setuptools -y
curl -O https://bootstrap.pypa.io/get-pip.py
sudo python get-pip.py
rm get-pip.py

}

###installing ansible

install_pip_packages() {

sudo pip install ansible --upgrade --user
sudo pip install --upgrade awscli --user
sudo pip install saws  --user
sudo pip install fabric --upgrade --user
sudo pip install virtualenv --upgrade --user
aws --version

}

###install java

install_java() {

sudo add-apt-repository ppa:webupd8team/java -y
sudo apt update -y
sudo apt install oracle-java8-installer -y
export JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre
java -version

}

###installing nodejs and yarn

install_node_yarn() {

curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt-get install nodejs -y
rm nodesource_setup.sh

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update
sudo apt-get install yarn -y

}

###installing docker and docker compose

install_docker() {

sudo apt-get update --fix-missing
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
sudo apt-cache policy docker-ce
sudo apt-get install -y docker-ce -y
sudo systemctl enable docker
sudo systemctl start docker
sudo usermod -aG docker ${USER}
sudo docker info

sudo curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
docker-compose --version

}

###installing packer

install_packer(){

sudo apt-get update --fix-missing
wget https://releases.hashicorp.com/packer/1.2.5/packer_1.2.5_linux_amd64.zip -O packer.zip
unzip packer.zip
sudo mv packer /usr/local/bin/
rm packer.zip
packer -v

}

###installing terraform

install_terraform(){

sudo apt-get update --fix-missing
wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip -O terraform.zip
unzip terraform.zip
sudo mv terraform /usr/local/bin/
rm terraform*
terraform -v

}

###installing kubectl-k8s administering tool

install_k8s() {

sudo apt-get update --fix-missing
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl
kubectl -v

}

###installing kubectl-k8s administering tool

install_k8s() {

sudo apt-get update --fix-missing
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl
kubectl -v

}
###installing saltstack

install_saltstack() {

sudo add-apt-repository ppa:saltstack/salt -y
sudo apt-get update
sudo apt-get install salt-master salt-minion salt-ssh salt-cloud salt-doc -y

}

###install and customize vim

install_vim() {

sudo apt-get update
sudo apt-get install vim -y
git clone --recursive https://github.com/jessfraz/.vim.git .vim
ln -sf $HOME/.vim/vimrc $HOME/.vimrc
cd $HOME/.vim
git submodule update --init

}

###customize bashrc

install_bashrc(){

sudo apt-get install node-rimraf lsscsi lm-sensors fortune-mod -y
git clone https://github.com/shudarshon/bashrc.git
cp bashrc/.bashrc $HOME/.bashrc
cp -r bashrc/.shells $HOME/
rm -rf bashrc

}

### install tilix

install_tilix(){

sudo add-apt-repository ppa:webupd8team/terminix -y
sudo apt-get update
sudo apt-get install tilix -y

}

###install chromium browser

install_chrome() {

sudo apt-get install chromium-browser -y

}

###install atom

install_atom() {

sudo add-apt-repository ppa:webupd8team/atom -y
sudo apt-get update
sudo apt-get install atom -y

}


###installing progam

install_essential
install_python_pip
install_pip_packages
install_java
install_node_yarn
install_docker
install_packer
install_terraform
install_k8s
install_saltstack

install_vim
install_bashrc
install_tilix

install_chrome
install_atom
